name: ğŸš€ Deploy website to develop on push with FTP

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy: # ä»»åŠ¡
    runs-on: ubuntu-latest # è¿è¡Œç¯å¢ƒ
    steps: # è¿è¡Œæ­¥éª¤
      - name: Checkout
        uses: actions/checkout@master # è·å–æºç 

      - name: Set Node Version
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install and Build
        run: |
          yarn install
          yarn build

      - name: ğŸ“‚ Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          # ftp server
          server: ftpupload.net
          # ftp username
          username: b32_28202196
          # ftp password
          password: ${{ secrets.FTP_PASSWORD }}
          # Folder to upload from, must end with trailing slash /
          local-dir: ./dist/
          # Path to upload to on the server. Must end with trailing slash /
          server-dir: /langnang-develop.ml/htdocs/vue-element-webstack/
